version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: kit5_postgres_db
        environment:
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'azeAZE123'
            POSTGRES_DB: 'kit5'
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    phppgadmin:
        image: dockage/phppgadmin
        container_name: phppgadmin
        environment:
        - PHP_PG_ADMIN_SERVER_HOST=db
        - PHP_PG_ADMIN_SERVER_PORT=5432
        - PHP_PG_ADMIN_SERVER_DEFAULT_DB=user
        ports:
        - "8080:80"
        depends_on:
        - db

volumes:
  db_data:

## docker exec -it kit5_postgres_db psql -U user -d kit5