version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: kit5_postgres_db
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: azeAZE123
            POSTGRES_DB: kit5
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    phppgadmin:
        image: dockage/phppgadmin
        container_name: phppgadmin
        environment:
            - PAGENATION=true
            - SERVER=db
        ports:
            - "8080:80"
        depends_on:
            - db
volumes:
  db_data:
