version: '3.8'
services:
  db:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'kit5'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'motdepasse'
        MYSQL_ROOT_PASSWORD: 'motdepasse_root'
      ports:
        - "3306:3306"
      volumes:
        - my_db_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
volumes:
  my_db_volume: